// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqmwIXt3m9XOQlyEvefYDEU1KGdNIMyhs',
    appId: '1:548031081093:web:e892ee624b52c2210417ec',
    messagingSenderId: '548031081093',
    projectId: 'marg-af127',
    authDomain: 'marg-af127.firebaseapp.com',
    storageBucket: 'marg-af127.firebasestorage.app',
    measurementId: 'G-E5VFS3HGS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVHvxg4KXUWQd8um7V25q30PhejSAETU0',
    appId: '1:548031081093:android:f8191f1c114d8ddd0417ec',
    messagingSenderId: '548031081093',
    projectId: 'marg-af127',
    storageBucket: 'marg-af127.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD8zFuYWk6GXSDp5XqgXuJbzH_s06miao',
    appId: '1:548031081093:ios:e9fe320f7f4fb4ca0417ec',
    messagingSenderId: '548031081093',
    projectId: 'marg-af127',
    storageBucket: 'marg-af127.firebasestorage.app',
    androidClientId: '548031081093-qjt0fpapa3085s0psl3q41bbtklt2a8u.apps.googleusercontent.com',
    iosClientId: '548031081093-gij9mff5acid6oh8o717pcevheifoalr.apps.googleusercontent.com',
    iosBundleId: 'com.example.marg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD8zFuYWk6GXSDp5XqgXuJbzH_s06miao',
    appId: '1:548031081093:ios:e9fe320f7f4fb4ca0417ec',
    messagingSenderId: '548031081093',
    projectId: 'marg-af127',
    storageBucket: 'marg-af127.firebasestorage.app',
    androidClientId: '548031081093-qjt0fpapa3085s0psl3q41bbtklt2a8u.apps.googleusercontent.com',
    iosClientId: '548031081093-gij9mff5acid6oh8o717pcevheifoalr.apps.googleusercontent.com',
    iosBundleId: 'com.example.marg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqmwIXt3m9XOQlyEvefYDEU1KGdNIMyhs',
    appId: '1:548031081093:web:b9ee57e52c975b380417ec',
    messagingSenderId: '548031081093',
    projectId: 'marg-af127',
    authDomain: 'marg-af127.firebaseapp.com',
    storageBucket: 'marg-af127.firebasestorage.app',
    measurementId: 'G-V8Q70CKQ0W',
  );

}